import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang="en" className="is-loading css-loading is-animating front is-desktop no-js">
      <head>
        {/* <link href='https://api.mapbox.com/mapbox-gl-js/v3.16.0/mapbox-gl.css' rel='stylesheet' />
         */}
        <link rel="stylesheet" href="https://unpkg.com/lenis@1.3.13/dist/lenis.css"></link>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased home wp-singular page-template-default page page-id-83 wp-theme-wickside page-homepage`}
      >
        {children}
      </body>
    </html>
  );
}
